### ISSUE TITLE
Firefox support 

### ISSUE THREAD

**Issue by VictorVow** [classvsoftware/under-new-management#1]
Thanks for making this extension, it looks super useful! Would love to see it on Firefox too as that's where I do most of my browsing.

**Comment by maxtheaxe** [comment]
I'd be happy to implement Firefox support this weekend.

**Comment by msfrisbie** [comment]
Firefox support requires me adding full Firefox Addons scraping support on the backend. TODO

**Comment by maxtheaxe** [comment]
I was [able to implement Firefox support](https://github.com/maxtheaxe/under-new-management-firefox) this afternoon. It [seems like service workers are still disabled in firefox](https://github.com/mozilla/web-ext/issues/2532)(?), so this version is using MV2 (hence why it wasn't just a pull request). I actually don't see any need for full AMO scraping in the backend—I'm just querying [the AMO API](https://mozilla.github.io/addons-server/topics/api/addons.html#detail) directly.

Still waiting on approval for the AMO listing. Not sure how long that'll be because none of my addons have ever required their in-depth review before (this does). Once it's approved, [it'll be available here](https://addons.mozilla.org/en-US/firefox/addon/under-new-management/). If you can't wait, [the first release is available now, on my repo](https://github.com/maxtheaxe/under-new-management-firefox/releases/tag/initial).

@msfrisbie happy to add you as an author to the AMO listing if you send me your details, we can probably work out some way to merge my code into your version later.

One additional note: I did do _some_ testing, but would love for people to do their best to break it and to report any issues they find.

**Comment by msfrisbie** [comment]
@maxtheaxe this is great! I wasn't aware the AMO had an API, that's way better.

For the purposes of adding Firefox support, I'm going to dump Parcel in favor of Plasmo so both builds can come from a single repo.

My plan is to fold in most of your changes into this repo.

**Comment by maxtheaxe** [comment]
Sounds good! Let me know which email you use for AMO and I'll add you to the listing.

I honestly hadn't heard of either parcel or plasmo prior to today, so I can't weigh in there, but the prospect of targeting MV2 _and_ MV3 on the same codebase sounds pretty cool. It's worth mentioning that there's probably(?) a better unified format in which to store addon/extension data—I was just trying to work within the confines of the chrome stuff.

I'm happy to add support for non-AMO extensions down the line as well, since Firefox allows installation of extensions distributed elsewhere.

Let me know how else I can help.

**Comment by maxtheaxe** [comment]
Just for the record, it's [live and installable from AMO](https://addons.mozilla.org/en-US/firefox/addon/under-new-management/) as of ~12 hours ago.

**Comment by VictorVow** [comment]
Thank you very much!

**Comment by Cerberus-tm** [comment]
> Just for the record, it's [live and installable from AMO](https://addons.mozilla.org/en-US/firefox/addon/under-new-management/) as of ~12 hours ago.

Thank you! Installed. Let us know in case you decide to sell your extension...
